plugin.name=Typography
plugin.category=miscellaneous
plugin.link=https://github.com/emes81/Smart-Typography-Plugin-for-OmegaT
plugin.author=Community contributors
plugin.description=Context-aware typographic punctuation while typing in OmegaT.
plugin.license=GNU General Public License version 3 or later
