id=en
name=English
languages=en,en-GB,en-US,en-AU,en-CA,en-IE,en-NZ,en-ZA
script=Latn
quotes.double.open=“
quotes.double.close=”
quotes.double.inner.open=none
quotes.double.inner.close=none
quotes.single.open=‘
quotes.single.close=’
quotes.single.inner.open=none
quotes.single.inner.close=none
apostrophe=’
spacing.before.semicolon=none
spacing.before.question=none
spacing.before.exclamation=none
spacing.before.colon=none
