id=fr
name=French
languages=fr,fr-FR,fr-BE,fr-LU,fr-MC
script=Latn
quotes.double.open=«
quotes.double.close=»
quotes.double.inner.open=nnbsp
quotes.double.inner.close=nnbsp
quotes.single.open=“
quotes.single.close=”
quotes.single.inner.open=none
quotes.single.inner.close=none
apostrophe=’
spacing.before.semicolon=nnbsp
spacing.before.question=nnbsp
spacing.before.exclamation=nnbsp
spacing.before.colon=nbsp
